# -*- coding: utf-8 -*-
"""fibonacci.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YkZ7H27U5azl0U_FEeJfKUqMked75uHL
"""

def generate_fibonacci(limit):
    fibonacci_seq = [0, 1]
    while True:
        next_num = fibonacci_seq[-1] + fibonacci_seq[-2]
        if next_num > limit:
          break
        fibonacci_seq.append(next_num)
    return fibonacci_seq
limit = int(input("Enter the limit for generating Fibonacci numbers: "))
print("Fibonacci sequence up to", limit, ":", generate_fibonacci(limit))