# -*- coding: utf-8 -*-
"""positive_int.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zsTa4Kq5SaTATbInbcrGQwx2C3phGLcM
"""

# Function to print all positive numbers in a list
def print_positive_numbers(input_list):
    positive_numbers = [num for num in input_list if num > 0]
    print("Output:", positive_numbers)

# Input lists
list1 = [12, -7, 5, 64, -14]
list2 = [12, 14, -95, 3]

# Call the function with input lists
print("Input:", "list1 =", list1)
print_positive_numbers(list1)

print("Input:", "list2 =", list2)
print_positive_numbers(list2)