# -*- coding: utf-8 -*-
"""Python_refresher_april.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16DbEotXS8ga0NK8gkG0j3mUZs1G-qlcZ
"""

print('hello world')

