# -*- coding: utf-8 -*-
"""Set_operation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EEBzybwCOkzUWgfJE4lINmpfC8y-829t
"""

# Define the two sets
E = {0, 2, 4, 6, 8}
N = {1, 2, 3, 4, 5}

# Perform set operations
union_result = E.union(N)
intersection_result = E.intersection(N)
difference_result = E.difference(N)
symmetric_difference_result = E.symmetric_difference(N)

# Print the results
print(f"Union of E and N is {union_result}")
print(f"Intersection of E and N is {intersection_result}")
print(f"Difference of E and N is {difference_result}")
print(f"Symmetric difference of E and N is {symmetric_difference_result}")